### ISSUE TITLE
browse api returns an error for directories with a space in them

### ISSUE THREAD

**Issue by wtlangford** [grimkor/DeckyFileServer#4]
Directories with a space in them return errors and can't be navigated to- likely because they're url-encoded when sent by the browser

**Comment by grimkor** [comment]
Yeah you're almost definitely right as to why, I'll take a look when I next get time and put in a fix.

Thanks for letting me know and I'll update this issue when I put in a fix.

**Comment by grimkor** [comment]
> Directories with a space in them return errors and can't be navigated to- likely because they're url-encoded when sent by the browser

Hey do you have the example of what was causing an error? I have given a try on directories with spaces in them and navigating as well as downloading files within them work.

Thanks

**Comment by wtlangford** [comment]
Hmm, I don't see this issue happening anymore, which is strange. Maybe something changed when I updated it to 0.1.4? I'm pretty sure I was on 0.0.2 before that

Either way, it seems to be working fine now

**Comment by grimkor** [comment]
> Hmm, I don't see this issue happening anymore, which is strange. Maybe something changed when I updated it to 0.1.4? I'm pretty sure I was on 0.0.2 before that
> 
> Either way, it seems to be working fine now

That sounds right. 0.0.2 was using a different backend which didn't handle encoding by default and from 0.1.x I changed to a far better backend, glad you updated and got it sorted!
