### ISSUE TITLE
can not access server due to firewall disallow

### ISSUE THREAD

**Issue by jees5555** [grimkor/DeckyFileServer#6]
SteamOS 3.5.5
Must Setting port 8000 TCP/UDP allow

Is it possible to auto allow the port when turn on the button？
or show a comment in the UI that user can setting firewall by thenselfves.

**Comment by grimkor** [comment]
Hey I just changed to 3.5.5 and did not need to configure any firewall ports to access port 8000.

Can you confirm what address you're trying to use and that you haven't installed any extra firewall software on the steam deck such as UFW?

**Comment by jees5555** [comment]
It's firewalld.
I removed the direct rules that i added before, and It still works.
sorry, it seems that there is no firewall issue.
I closed this issues.
