### ISSUE TITLE
Preview images

### ISSUE THREAD

**Issue by threkk** [grimkor/DeckyFileServer#9]
My use case for this plugin is to open the server in a folder of my steam deck where all my screenshots are located. It would be amazing if the plugin was able to preview the pictures, even if it is only a small thumbnail. I am open to contributing with code if necessary.

**Comment by grimkor** [comment]
Hey i was away on holiday and I have been taking a look at this today

Got a solution that should work but looking to see if it can get it to refresh the page nicely once all thumbnails are created for a page and I need to fix an issue when there's thousands of images in a single folder which blocks the page from loading.

Example of how it currently looks below:

![Screenshot_20240225-192246~2.png](https://github.com/grimkor/DeckyFileServer/assets/19330133/5ec6e9bc-2fa2-4726-bf79-1e272651c0ce)

**Comment by grimkor** [comment]
Morning @threkk v0.3.0 is now available in the Decky Plugin store which has previews for images and videos.

Going to close this issue and I hope you enjoy the update!
